apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.api.name }}-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.transacttrace.io
      secretName: transacttrace-tls
  rules:
    - host: api.transacttrace.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.api.name }}-svc
                port:
                  number: {{ .Values.api.port }}
          - path: /ml
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ml.name }}-svc
                port:
                  number: {{ .Values.ml.port }}
